### ISSUE TITLE
Comments on Site Planning Tips

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s-enduser#40]
On the branch planningtips, take a look at the page "[s-planning-tips](https://github.com/omeka/omeka-s-enduser/blob/planningtips/docs/s-planning-tips.md)." What is it missing? What needs to be corrected?

**Comment by sharonmleon** [comment]
I would say that we need a little bit more elaboration about the ways that the block system works on the pages to let users build out their sites. They'll have to do layout planning for each page, since there aren't any stock pages.

Also, it looks like there are set of questions after the navigation material that would naturally lead into this discussion. They're not broken out and bold, but they're there.

Currently, there are no questions about Item Sets. Probably should be.

Should we say something about using your own items and/or those of others included in the larger installation?

Something about customizing search? Part of the larger topic of how users will find materials in the site?

**Comment by mebrett** [comment]
Revised version available, same branch.
