### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by the-redshoes** [omeka/omeka-s-enduser#57]
Hello,
I'm newbie on github, but I'd like to translate the enduser manual in french, because there's a lot of users in France or person interested in, so I've made a fork to begin the translation.
`https://github.com/the-redshoes/omeka-s-enduser--Fr-version
`
But before I go ahead, I'd like to know if there's projects like these that already exists ?
So I can join instead of creating one more.
If  not, well, come in ! :)

**Comment by mebrett** [comment]
As far as I know, there is not an active translation project. If you haven't already, you might check with the folks at https://omeka.fr/

**Comment by jeau** [comment]
Hi, 
Sorry, I answer quite late.
 
That's a good idea. I had started this work 3 years ago with the first versions of Omeka
https://github.com/jeau/omeka-s-enduser-fr

I had not continued because my English is not very good and I no longer had time to follow the developments of Omeka S. We can resume this work.

I am a member of the omeka.fr team

**Comment by the-redshoes** [comment]
Hi / Bonjour ! 
Tks Thierry. I think that it will be ok with texts and that's just a question of time, but  maybe it's about making french printscreens that I may need some help.
I go on and I'll contact you by mail.

/ 
Merci Thierry. Je pense que ça va aller avec les textes, et que c'est plus une question de temps pour gérer, mais c'est plutôt sur les prises d'écrans en français que je risque de solliciter de l'aide.

J'avance et je te recontacte par mail.

Gladys
